package edu.groupeighteen.librarydbms.control.entities;

import edu.groupeighteen.librarydbms.control.db.DatabaseHandler;
import edu.groupeighteen.librarydbms.model.db.QueryResult;
import edu.groupeighteen.librarydbms.model.entities.Item;
import edu.groupeighteen.librarydbms.model.exceptions.ItemNotFoundException;

import java.sql.*;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * @author Mattias Fridsén
 * @project LibraryDBMS
 * @package edu.groupeighteen.librarydbms.control.entities
 * @contact matfir-1@student.ltu.se
 * @date 5/5/2023
 *
 * This class contains database CRUD operation methods as well as other methods related to the Item entity class.
 * It contains a list of all Item titles for quicker validation.
 */
public class ItemHandler {
    /**
     * Used to speed up searching
     */
    private static Map<String, Integer> storedTitles = new HashMap<>();

    /**
     * Syncs the storedTitles against the items table.
     *
     * @throws SQLException if there's an error executing the SQL query
     */
    public static void setup() throws SQLException {
        syncTitles();
    }

    /**
     * Syncs the storedTitles by retrieving titles from the items table.
     *
     * @throws SQLException if there's an error executing the SQL query
     */
    public static void syncTitles() throws SQLException {
        if (!storedTitles.isEmpty()) {
            storedTitles.clear();
        }
        storedTitles = retrieveTitlesFromTable();
    }

    /**
     * Retrieves titles from the items table and returns them as a map with title-count pairs.
     *
     * @return a map of titles and their counts
     * @throws SQLException if there's an error executing the SQL query
     */
    private static Map<String, Integer> retrieveTitlesFromTable() throws SQLException {
        // Execute the query to retrieve all titles
        QueryResult result = DatabaseHandler.executeQuery("SELECT title, count(*) as count FROM items GROUP BY title ORDER BY title ASC");
        Map<String, Integer> titles = new HashMap<>();

        // Add the retrieved titles to the map
        while (result.getResultSet().next()) {
            titles.put(result.getResultSet().getString("title"), result.getResultSet().getInt("count"));
        }

        // Close the resources
        result.close();
        return titles;
    }

    /**
     * Prints the stored titles and their counts.
     */
    public static void printTitles() {
        System.out.println("\nTitles:");
        storedTitles.forEach((title, count) -> System.out.println("Title: " + title + " Available: " + count));
    }

    /**
     * Returns the storedTitles map.
     *
     * @return the storedTitles map
     */
    public static Map<String, Integer> getStoredTitles() {
        return storedTitles;
    }

    /**
     * Sets the storedTitles map.
     *
     * @param storedTitles the map of titles and their counts to set
     */
    public static void setStoredTitles(Map<String, Integer> storedTitles) {
        ItemHandler.storedTitles = storedTitles;
    }

    /**
     * Prints the list of items with their IDs and titles.
     *
     * @param itemList the list of items to print
     */
    public static void printItemList(List<Item> itemList) {
        System.out.println("Items:");
        int count = 1;
        for (Item item : itemList) {
            System.out.println(count + " itemID: " + item.getItemID() + ", title: " + item.getTitle());
        }
    }



    public static Item createNewItem(String title) throws SQLException {
        if (title == null || title.isEmpty())
            throw new IllegalArgumentException("Empty title.");

        Item newItem = new Item(title);
        newItem.setItemID(saveItem(newItem));

        storedTitles.put(newItem.getTitle(), storedTitles.getOrDefault(newItem.getTitle(), 0) + 1);
        return newItem;
    }

    /**
     * Saves an Item object to the database.
     *
     * This method attempts to insert a new item into the 'item' table. It uses the title property of the
     * provided Item object to populate the new record. The database is expected to generate
     * a unique ID for each new item, which is retrieved and returned by this method.
     *
     * @param item the Item object to be saved. This object should have a title set.
     * @return the unique itemID generated by the database for the new item record.
     * @throws SQLException If an error occurs while interacting with the database, or if the database does not
     *      generate a new unique ID for the inserted item.
     */
    public static int saveItem(Item item) throws SQLException {
        //Validate input
        if (item == null)
            throw new IllegalArgumentException("Invalid item: item is null.");

        //Prepare query
        String query = "INSERT INTO items (title) VALUES (?)"; //Update these two when more fields are added, as well as javadoc
        String[] params = {item.getTitle()}; //Update these two when more fields are added, as well as javadoc

        //Execute query and get the generated itemID, using try-with-resources
        try (QueryResult queryResult = DatabaseHandler.executePreparedQuery(query, params, Statement.RETURN_GENERATED_KEYS)) {
            ResultSet generatedKeys = queryResult.getStatement().getGeneratedKeys();
            if (generatedKeys.next()) return generatedKeys.getInt(1);
            else throw new SQLException("Failed to insert the item, no ID obtained.");
        }
    }

    //TODO-exception might want to throw a custom exception (like ItemNotFoundException) instead of returning null,
    //to make error handling more consistent
    /**
     * Retrieves a Item object from the database based on the provided item ID.
     *
     * This method attempts to retrieve the item details from the 'items' table in the database
     * that correspond to the provided item ID. If a item with the given ID exists, a new Item object
     * is created with the retrieved title and the item's ID is set.
     *
     * @param itemID The unique ID of the item to be retrieved.
     * @return The Item object corresponding to the provided ID, or null if no such item is found.
     * @throws SQLException If an error occurs while interacting with the database
     */
    public static Item getItemByID(int itemID) throws SQLException {
        //No point getting impossible items
        if (itemID <= 0) { //TODO-exception IllegalArgumentException
            System.err.println("Error retrieving item by itemID: invalid itemID " + itemID); //TODO-log
            return null;
        }

        //Prepare a SQL query to select an item by itemID.
        String query = "SELECT title FROM items WHERE itemID = ?";
        String[] params = {String.valueOf(itemID)};

        //Execute the query and store the result in a ResultSet.
        QueryResult queryResult = DatabaseHandler.executePreparedQuery(query, params);

        try (queryResult) {
            ResultSet resultSet = queryResult.getResultSet();
            //If the ResultSet contains data, create a new Item object using the retrieved title
            //and set the item's itemID.
            if (resultSet.next()) {
                String title = resultSet.getString("title");
                Item item = new Item(title);
                item.setItemID(itemID);
                return item;
            }
        }
        //Close the resources.

        //Return null if not found.
        return null;
    }

    //TODO-exception might want to throw a custom exception (like ItemNotFoundException) instead of returning null,
    //to make error handling more consistent
    /**
     * Retrieves a Item object from the database based on the provided title.
     *
     * This method attempts to retrieve the item details from the 'items' table in the database
     * that correspond to the provided title. If a item with the given title exists, a new Item
     * object is created with the retrieved title.
     *
     * @param title The title of the item to be retrieved.
     * @return The Item object corresponding to the provided title, or null if no such item is found.
     * @throws SQLException If an error occurs while interacting with the database
     */
    public static Item getItemByTitle(String title) throws SQLException {
        //No point getting invalid items
        if (title == null || title.isEmpty()) { //TODO-exception IllegalArgumentException
            System.err.println("Error retrieving item by title: empty title."); //TODO-log
            return null;
        }

        //Prepare a SQL query to select an item by title.
        String query = "SELECT itemID FROM items WHERE title = ?";
        String[] params = {title};

        //Execute the query and store the result in a ResultSet.
        try (QueryResult queryResult = DatabaseHandler.executePreparedQuery(query, params)) {
            ResultSet resultSet = queryResult.getResultSet();
            //If the ResultSet contains data, create a new Item object using the retrieved title,
            //and set the item's itemID.
            if (resultSet.next()) {
                Item item = new Item(title);
                item.setItemID(resultSet.getInt("itemID"));
                return item;
            }
        }
        //Return null if not found.
        return null;
    }



    public static boolean updateItem(Item item) throws SQLException {
        // Validate the input
        if (item == null)
            throw new IllegalArgumentException("Invalid item: item is null.");
        if (item.getItemID() <= 0)
            throw new IllegalArgumentException("Invalid item: itemID must be greater than 0.");

        // Get the old title
        String oldTitle = getItemTitleById(item.getItemID());

        // Prepare a SQL command to update an item's title by itemID.
        String sql = "UPDATE items SET title = ? WHERE itemID = ?";
        String[] params = {item.getTitle(), String.valueOf(item.getItemID())};

        // Execute the update.
        int rowsAffected = DatabaseHandler.executePreparedUpdate(sql, params);

        // If the update was successful, update the storedTitles
        if (rowsAffected == 1) {
            // Decrement the count of the old title. Remove the entry if the count reaches 0.
            storedTitles.put(oldTitle, storedTitles.get(oldTitle) - 1);
            if (storedTitles.get(oldTitle) == 0) {
                storedTitles.remove(oldTitle);
            }

            // Increment the count of the new title. Add a new entry if the title does not exist yet.
            storedTitles.put(item.getTitle(), storedTitles.getOrDefault(item.getTitle(), 0) + 1);
        }

        return rowsAffected == 1;
    }

    private static String getItemTitleById(int itemId) throws SQLException {
        String sql = "SELECT title FROM items WHERE itemID = ?";
        String[] params = {String.valueOf(itemId)};
        QueryResult queryResult = DatabaseHandler.executePreparedQuery(sql, params);

        if(queryResult.getResultSet().next()){
            return queryResult.getResultSet().getString("title");
        }else{
            throw new SQLException("Item with ID " + itemId + " does not exist.");
        }
    }



    public static boolean deleteItem(Item item) throws SQLException, ItemNotFoundException {
        //Validate the input
        if (item == null)
            throw new IllegalArgumentException("Invalid item: item is null.");
        if (item.getItemID() <= 0)
            throw new IllegalArgumentException("Invalid item: itemID must be greater than 0.");

        // Check if the item exists in the database
        String sql = "SELECT COUNT(*) FROM items WHERE itemID = ?";
        String[] params = {String.valueOf(item.getItemID())};

        QueryResult queryResult = DatabaseHandler.executePreparedQuery(sql, params);
        ResultSet resultSet = queryResult.getResultSet();
        resultSet.next(); // Move to the first row

        // If the item does not exist, throw an exception
        if (resultSet.getInt(1) == 0) {
            queryResult.close();
            throw new ItemNotFoundException(item.getItemID());
        }

        queryResult.close();

        //Prepare a SQL command to delete a item by itemID.
        sql = "DELETE FROM items WHERE itemID = ?";
        params = new String[]{String.valueOf(item.getItemID())};

        //Execute the update.
        int rowsAffected = DatabaseHandler.executePreparedUpdate(sql, params);

        //Check if the delete was successful (i.e., if any rows were affected)
        if (rowsAffected > 0) {
            // Decrement the count of the item's title. Remove the entry if the count reaches 0.
            storedTitles.put(item.getTitle(), storedTitles.get(item.getTitle()) - 1);
            if (storedTitles.get(item.getTitle()) == 0) {
                storedTitles.remove(item.getTitle());
            }
            return true;
        }

        return false;
    }


    //TODO-test
    //TODO-comment
    //TODO-implement
    //TODO-exception
    public static int getAllowedRentalDaysByID(int itemID) throws SQLException {
        Item item = getItemByID(itemID);
        if (item != null) return item.getAllowedRentalDays();
        else throw new IllegalArgumentException("Couldn't find item with ID: " + itemID);
    }
}